Introduces two calls to decoupled api
ucb-bar/chisel-testers2 pull request #326
Opened 2021-06-10 19:43 UTC by chick

New methods for providing back pressure and input stalling on tests of decoupled interfaces
- notReady()
- notValid()
These can be used to introduce
- back pressure
- input stall
To a test of a dut with decoupled interface test provided to show use.

2021-06-10 19:44 UTC, chick commented
This replaces #306 with a cleaner interface and a
test with decent examples.

2021-06-13 05:16 UTC, ducky64 commented
Are you sure these are necessary? The current implementation of [`initSource` ](https://github.com/ucb-bar/chisel-testers2/blob/master/src/main/scala/chiseltest/DecoupledDriver.scala#L12) and [`initSink`](https://github.com/ucb-bar/chisel-testers2/blob/master/src/main/scala/chiseltest/DecoupledDriver.scala#L62) set valid and ready to false, which is intended to be the default state unless temporarily overridden by something like `enqueue` or `expectDequeue`.

Also, are you sure about the implementation? The idea of a timescope is that the pokes inside disappear (and revert) at the end of a timescope. As written, it seems you open a timescope, do a poke, and immediately close the timescope - so it effectively shouldn't do anything. Typically the idea with a timescope is that it should do some kind of operation that advances time, like stepping on a block.

Note that this PR seems to follows the common latching pokes style of writing tests, where you would have to remember to poke (for example) valid = false after asserting valid = true for one transaction. In contrast, the chiseltest style provides a default and a time-scoped temporary override, with the system handling the revert for you.

2021-06-21 18:02 UTC, chick commented
@ducky64 Several points:
- I could not get this to work without wrapping using `timescope`s in `notReady` and `notValid`
  - I was unable to get the tests in `DecoupledBackPressureInputStallTest` to work using `initSource` and `initSink`
  - Maybe you could provide an example of how you see the API on this.
- Motivation for this was @wunderabt trying to construct a decoupled back-pressure example for the bootcamp
  - They tried using a slower clock in the module to create the back-pressure but that approach has a lot of problems.
- I'm a big believer in TBUINU "the best UI is no UI", it follows
  - Back-pressure should be built-in to the decoupled tools in some way that is clear and painless
  - Maybe `enqueue`, `dequeue` family could have additional arguments, with good defaults.
  - Maybe @ekiwi has some ideas here.
    - We should make it hard to write tests of decoupled interfaces that don't handle back-pressure
- If this turns out to be really complicated I think we should make some small step that will let us get a bootcamp example

2021-06-25 21:31 UTC, chick commented
These errors should be fixed by PR #329

2021-07-22 15:10 UTC, ekiwi approved these changes
LGTM

2021-07-24 19:01 UTC, ducky64 requested changes
Mostly looks good, some stylistic issues.

2021-07-24 19:01 UTC, ducky64 commented on src/test/scala/chiseltest/tests/DecoupledBackPressureInputStallTest.scala
> +  val cycles = IO(Output(UInt(32.W)))
In a proper design, this wouldn't be part of the DUT right? This is pure test instrumentation? Can this be moved into the test harness, or if a cycle count isn't available yet (is it?) can we have a TODO for it?

2021-08-18 17:41 UTC, chick commented
Closing as this is more of an example than a test. This was prompted by [Bootcamp PR 153](https://github.com/freechipsproject/chisel-bootcamp/pull/153). 153 has been closed as I believe the DecoupledGCD code demonstrates back-pressure handling already

2021-08-18 17:41 UTC, closed without merging