simulator: add new low level abstraction layer
ucb-bar/chisel-testers2 pull request #337
Opened 2021-07-21 23:57 UTC by ekiwi

This is my attempt to split https://github.com/ucb-bar/chisel-testers2/pull/334 into two PRs.

This PR just adds the new low-level `Simulator` abstraction, whereas https://github.com/ucb-bar/chisel-testers2/pull/334 is going to actually replace the old backend infrastructure and thus expose the new implementation to the user.

2021-07-29 21:26 UTC, chick requested changes
There's mostly a few files that are missing a newline at end of file.

2021-07-29 21:26 UTC, chick commented on src/test/scala/chiseltest/simulator/ComplianceTest.scala
> +private object DefaultTag extends Tag("DefaultTag")
```suggestion
private object DefaultTag extends Tag("DefaultTag")

```

2021-07-29 21:26 UTC, chick commented on src/test/scala/chiseltest/simulator/Icarus.scala
> +}
```suggestion
}

```

2021-07-29 21:26 UTC, chick commented on src/test/scala/chiseltest/simulator/Treadle.scala
> +}
```suggestion
}

```

2021-07-29 21:26 UTC, chick commented on src/test/scala/chiseltest/simulator/Vcs.scala
> +}
```suggestion
}

```

2021-07-29 21:26 UTC, chick commented on src/test/scala/chiseltest/simulator/Verilator.scala
> +}
```suggestion
}

```

2021-07-29 21:29 UTC, chick commented on src/main/scala/chiseltest/simulator/Simulator.scala
> +  def findVersions: Unit
This probably should be done under a separate style based PR

2021-07-29 21:29 UTC, chick commented on src/main/scala/chiseltest/simulator/Simulator.scala
> +  def getCoverage(): List[(String, Long)] =
Also to be done on separate PR

2021-07-29 21:30 UTC, chick commented on src/main/scala/chiseltest/simulator/IcarusSimulator.scala
> +    val verilogState = Compiler.lowFirrtlToSystemVerilog(state, passes)
Compiler call is necessary, verilogState is unused

2021-07-29 22:44 UTC, ekiwi commented on src/main/scala/chiseltest/simulator/Simulator.scala
> +  def findVersions: Unit
good catch, fixed!

2021-07-29 22:44 UTC, ekiwi commented on src/main/scala/chiseltest/simulator/Simulator.scala
> +  def getCoverage(): List[(String, Long)] =
I would prefer to keep the parenthesis since this function will involve file system access. Thus it is more than a simple accessor.

2021-07-29 22:45 UTC, ekiwi commented on src/main/scala/chiseltest/simulator/IcarusSimulator.scala
> +    val verilogState = Compiler.lowFirrtlToSystemVerilog(state, passes)
removed

2021-07-30 17:17 UTC, chick approved these changes
I think this looks good.
Lot's of testing has been done.

2021-07-30 17:20 UTC, merged

2021-07-30 22:33 UTC, sequencer commented
This seems breaks on my side:
https://github.com/sequencer/chipsalliance-playground/runs/3205771865?check_suite_focus=true

2021-07-30 22:38 UTC, ekiwi commented
> This seems breaks on my side:
> https://github.com/sequencer/chipsalliance-playground/runs/3205771865?check_suite_focus=true

Thanks for letting me know. What Java version are you running your tests with?

2021-07-30 22:42 UTC, sequencer commented
OpenJDK16

2021-07-30 23:08 UTC, ekiwi commented
@sequencer Could you please review this potential fix: https://github.com/ucb-bar/chisel-testers2/pull/350 ?