Iotesters compat
ucb-bar/chisel-testers2 pull request #348
Opened 2021-07-30 00:24 UTC by ekiwi

This is an experiment based on: https://github.com/ucb-bar/chisel-testers2/pull/334

The idea here is that providing a (mostly) backwards compatible API we can finally deprecate the original `chisel-testers` repo.

2021-08-05 19:48 UTC, chick requested changes
Basically looks fine.
Tests pass for me.
There were some ugly warning messages which went away when suggested changes to BlackBoxDeliverySpec and AddTwoAddThree are applied. I'm not sure about them but I'd rather not propagate wrong code 
A number of small fixes requested

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/LoggingUsageSpec.scala
> +      Logger.makeScope() {
```suggestion
      makeScope(Seq.empty[Annotation]) {
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/LoggingUsageSpec.scala
> +import logger.{LazyLogging, Logger}
```suggestion
import firrtl.annotations.Annotation
import logger.Logger.makeScope
import logger.{LazyLogging, Logger}
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/LoggingUsageSpec.scala
> +      Logger.makeScope() {
```suggestion
      makeScope(Seq.empty[Annotation]) {
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/LoggingUsageSpec.scala
> +      Logger.makeScope() {
```suggestion
      makeScope(Seq.empty[Annotation]) {
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/MemPokeSpec.scala
> +  * Trying to make sure memory does not get DCE'd or flagged as unitialized.
```suggestion
  * Trying to make sure memory does not get DCE'd or flagged as uninitialized.
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/ComplexMemoryLoadingSpec.scala
> +import chisel3.util.experimental.{loadMemoryFromFile, loadMemoryFromFileInline}
```suggestion
import chisel3.util.experimental.loadMemoryFromFileInline
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/GCDCalculator.scala
> +  def computeGcdResultsAndCycles(a: Int, b: Int, depth: Int = 1): (Int, Int) = {
```suggestion
  @tailrec
  def computeGcdResultsAndCycles(a: Int, b: Int, depth: Int = 1): (Int, Int) = {
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/LoadMemoryFromFileSpec.scala
> +import chisel3.util.experimental.{loadMemoryFromFile, loadMemoryFromFileInline}
```suggestion
import chisel3.util.experimental.loadMemoryFromFileInline
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/LoadMemoryFromFileSpec.scala
> +import org.scalatest.flatspec.AnyFlatSpec
```suggestion
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/MultiIOModule.scala
> +import org.scalatest.freespec.AnyFreeSpec
```suggestion
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/PeekPokeBundleSpec.scala
> +    val myBundleMap : LinkedHashMap[String, BigInt] = LinkedHashMap[String, BigInt]() ++ List[(String, BigInt)](
```suggestion
    val myBundleMap : mutable.LinkedHashMap[String, BigInt] = mutable.LinkedHashMap[String, BigInt]() ++ List[(String, BigInt)](
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/PeekPokeBundleSpec.scala
> +import scala.collection.mutable.LinkedHashMap
```suggestion
import scala.collection.mutable
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/PeekPokeBundleSpec.scala
> +      ("anEnum" -> MyEnum.e1)
```suggestion
      "aUInt4"	-> BigInt(3) ,
      "aSInt5"	-> BigInt(2),
      "aBundle.aBool"	-> BigInt(1),
      "aBottomBool"	-> BigInt(0),
      "anEnum" -> MyEnum.e1
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/PeekPokeBundleSpec.scala
> +      ("anEnum" -> MyEnum.e1)
```suggestion
    val myBundleMap : mutable.LinkedHashMap[String, BigInt] = mutable.LinkedHashMap[String, BigInt]() ++ List[(String, BigInt)](
      "aUInt4"	-> BigInt(4),
      "aSInt5"	-> BigInt(5),
      "aBundle.aBool"	-> BigInt(0),
      "aBottomBool"	-> BigInt(1),
      "anEnum" -> MyEnum.e1
```

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/examples/SecondClockDrivesRegisterSpec.scala
> +import org.scalatest.flatspec.AnyFlatSpec
```suggestion
```

2021-08-05 19:48 UTC, chick commented on src/test/resources/iotesters/AddTwoAddThree.v
> +  out <= in + 2;
```suggestion
    out = in + 2;
```
This makes a pretty ugly warning message go away. Test seems to pass anyway. But I don't know quite enough verilog to know if this is the right thing to do

2021-08-05 19:48 UTC, chick commented on src/test/resources/iotesters/AddTwoAddThree.v
> +  out <= in + 3;
```suggestion
    out = in + 3;
```
This makes a pretty ugly warning message go away. Test seems to pass anyway. But I don't know quite enough verilog to know if this is the right thing to do

2021-08-05 19:48 UTC, chick commented on src/test/scala/chiseltest/iotesters/BlackBoxVerilogDeliverySpec.scala
> +    |  out <= in + 1;
```suggestion
    |    out = in + 1;
```
This makes a pretty ugly warning message go away. Test seems to pass anyway. But I don't know quite enough verilog to know if this is the right thing to do

2021-08-05 20:29 UTC, ekiwi commented on src/main/scala/chiseltest/iotesters/PeekPokeTester.scala
> +  def poke[T <: Element: Pokeable](signal: T, value: Int):  Unit = poke(signal, BigInt(value))
This happens a couple of times, I am trying to replace `T` with `E` in all of them,.

2021-08-05 23:01 UTC, chick approved these changes
This looks good to me. It seems to offer the easiest path to gently moving people from iotesters to chiseltest. @ducky64 should weigh in.

2021-08-17 20:16 UTC, ducky64 approved these changes
This looks fine, especially if it's basically a copypaste of large chunks of iotesters. It might be worth adding a comment to those classes that they were copied from iotesters, and perhaps also a summary of any changes made.

2021-08-17 21:22 UTC, merged