Add Observer trait and function for Boringtools submodule drilling
ucb-bar/chisel-testers2 pull request #407
Opened 2021-10-12 17:01 UTC by carlosedp

This PR adds the Observer trait that can be used on wrapper modules for looking into submodules on chiseltest.

The wrapper makes sure the observed objects are only created in the object instantiation during the test and not Verilog generation (creating the observed wires).

## Usage

Create a Chisel module that instantiates a submodule as usual:

```scala
import chisel3._

// This is the module and submodule to be tested
class SubModule extends Module {
  val reg  = Reg(UInt(6.W))
  reg := 42.U
}

// Top module which instantiates the submodule
class Top extends Module {
  val submodule = Module(new SubModule)
}

// Generate the main project Verilog
object Proj extends App {
 (new chisel3.stage.ChiselStage).emitVerilog(
   new Top()
)}
```

In the test, wrap the top module adding the `Observer` trait and inside it use the `observe` method pointing to submodule objects. Use this wrapper as the DUT and the observed objects will be available for testing:

```scala
import chisel3._
import chiseltest._
import org.scalatest._

import flatspec._
import matchers.should._
import chiseltest.experimental.Observer

// Here we create a wrapper extending the Top module to add the `Observer` trait
class TopWrapper extends Top with Observer {
  // Observe the submodule "reg" Register
  val observed_reg  = observe(submodule.reg)
}

it should "observe a submodule Reg by using BoringUtils" in {
  test(new TopWrapper) { c =>
    c.observed_reg.expect(42.U)
  }
}
```

2021-10-21 10:25 UTC, sequencer commented
I personally suggest using VPI and chipsalliance/chisel3#2077 to achieve this feature.

2021-10-21 22:19 UTC, ekiwi commented
Short status update: @carlosedp I think that you are correct in that we should not make this more complicated than we have to.

My thinking right now:
- do we actually need this to be a trait? We could also just make `observe` a free function that people can call as a somewhat nicer interface to BoringUtils
- I would prefer if `observe` did not create an I/O by default. Sometimes you just need to observe an internal signal in order to write a property about it: https://github.com/ucb-bar/chisel-testers2/blob/b990df45adaa4e69d9c49029ae705ddef4ddd8fe/src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala#L163
- maybe we can also add an `expose` function which calls `observe` and adds an output port

2021-11-01 18:30 UTC, carlosedp commented
Do you think this is a "go"? :)

2021-11-01 18:35 UTC, ekiwi commented
> Do you think this is a "go"? :)

Oh, sorry @carlosedp, my research is keeping my busy so I forgot about this PR.

I would prefer if you could create a `observe` and `expose` function, where `observe` creates a `Wire` and only `expose` will create an `IO` port. You can create the function with an `object` and the `apply` method like:
```.scala
object observe {
  def apply[T <: Data](signal: T): T = {
    val wire = WireInit(0.U.asTypeOf(chiselTypeOf(signal)))
    BoringUtils.bore(signal, Seq(wire))
    wire
  }
}

object expose {
  def apply[T <: Data](signal: T): T = {
    val ob = IO(Output(chiselTypeOf(signal)))
    ob := 0.U.asTypeOf(chiselTypeOf(signal))
    BoringUtils.bore(signal, Seq(ob))
    ob
  }
}
```

2021-11-01 19:21 UTC, carlosedp commented
I think this is way better. Not needing to use the Observer trait makes things clearer.

2021-11-01 19:29 UTC, carlosedp commented
Would you give me a heads-up on the usage of the `obseve` function? I'd add a use case for it too.

2021-11-01 19:32 UTC, ekiwi commented
> Would you give me a heads-up on the usage of the `obseve` function? I'd add a use case for it too.

That would be awesome. A good starting point would be to:
- delete the `Observer` trait here: https://github.com/ucb-bar/chisel-testers2/blob/b990df45adaa4e69d9c49029ae705ddef4ddd8fe/src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala#L162
- you could use this as an example of how to use `observe`: https://github.com/ucb-bar/chisel-testers2/blob/b990df45adaa4e69d9c49029ae705ddef4ddd8fe/src/test/scala/chiseltest/formal/examples/VGBComparisonOfFormalAndSimulation.scala#L35

2021-11-01 19:51 UTC, carlosedp commented
Done, I've replaced the previous `Observer` trait in two places.

2021-11-01 19:54 UTC, ekiwi requested changes
Four small changes and then we can get this in!

2021-11-01 19:54 UTC, ekiwi commented on src/main/scala/chiseltest/experimental/Observe.scala
> +    *      able to observe the submodule:
should be something like: "while exposing the signal from the submodule to the testbench"

2021-11-01 19:54 UTC, ekiwi commented on src/main/scala/chiseltest/experimental/Observe.scala
> +    * it should "observe a submodule Reg by using BoringUtils" in {
"expose"

2021-11-01 19:54 UTC, ekiwi commented on src/main/scala/chiseltest/experimental/Observe.scala
> +    *   the signal to be observed
"exposed"

2021-11-01 19:54 UTC, ekiwi commented on src/test/scala/chiseltest/experimental/tests/ObserveTest.scala
> +class ObserverTest extends AnyFlatSpec with ChiselScalatestTester with Matchers {
Please rename to `ObserveExposeTests` (class and filename)

2021-11-01 20:00 UTC, ekiwi approved these changes
LGTM :shipit:

2021-11-01 20:18 UTC, merged

2021-11-01 20:34 UTC, carlosedp commented
Something went wonky with the master tests...
https://github.com/ucb-bar/chisel-testers2/runs/4072541570?check_suite_focus=true